Main svc
vladislavStel/java-explore-with-me pull request #4
Opened 2023-09-01 21:28 UTC by vladislavStel

2023-09-02 06:47 UTC, sergeymamonov requested changes
В качестве улучшения классы dto можно сделать иммутабельными. Можно добавить в @FieldDefaults указание, чтобы поля были final. И добавить final к классу.

2023-09-02 06:47 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/category/controller/PublicCategoryController.java
> +                                           @RequestParam(name = "size", defaultValue = "10", required = false) int size) {
Клиент может передать невалидные значения пагинации. Поэтому лучше добавить валидацию.

2023-09-02 06:47 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/event/service/EventService.java
> +    List<EventShortDto> findEventsBySearchQueryAndSort(String text, List<Long> categories, Boolean paid,
Если в метод нужно передать много параметров, то лучше сделать объект, в который положить все эти параметры. И тогда в метод нужно будет передать только один этот объект. Плюс если добавится еще один параметр, который нужно будет передать в метод, то нужно будет добавить поле в класс. Сигнатура метода при этом не изменится.

2023-09-02 06:47 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/location/dto/LocationDto.java
> +import lombok.*;
Лучше не использовать импорт через *, так как это может приводить к конфликтам импорта из разных пакетов.

2023-09-02 06:47 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/exception/ErrorHandler.java
> +    @ExceptionHandler(ConflictException.class)
Конфликт (такой вывод можно сделать из названия ошибки) не может приводить к запрету доступа. Либо название ошибки нужно изменить, либо статус.

2023-09-02 06:47 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/exception/ErrorHandler.java
> +    @ExceptionHandler(ValidationException.class)
Ошибка валидации - это не конфликт. Либо название ошибки, либо статус нужно изменить.

2023-09-02 06:47 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/exception/ErrorHandler.java
> +    @ExceptionHandler(IncorrectlyRequestException.class)
Ниже методы одинаковые, а в этой аннотации можно писать через запятую исключения, поэтому можно соединить все методы ниже в один со статусом 400/

2023-09-02 06:47 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/event/controller/PublicEventController.java
> +        statisticService.addHit(request);
Зачем отправлять запрос в клиент из контроллера. Это логика работы, поэтому ее нужно перенести в сервис.

2023-09-02 06:47 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/user/service/UserServiceImpl.java
> +        Pageable page = PageRequest.of(from / size, size);
Здесь возможно деление на ноль, так как параметры пагинации не валидируются.

2023-09-02 07:16 UTC, vladislavStel commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/location/dto/LocationDto.java
> +import lombok.*;
Idea автоматом меняет на *

2023-09-02 10:09 UTC, vladislavStel commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/user/service/UserServiceImpl.java
> +        Pageable page = PageRequest.of(from / size, size);
добавил валидацию.

2023-09-02 13:28 UTC, vladislavStel commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/event/controller/PublicEventController.java
> +        statisticService.addHit(request);
перенес в сервис

2023-09-02 13:28 UTC, vladislavStel commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/exception/ErrorHandler.java
> +    @ExceptionHandler(IncorrectlyRequestException.class)
переделал

2023-09-02 13:28 UTC, vladislavStel commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/exception/ErrorHandler.java
> +    @ExceptionHandler(ValidationException.class)
изменил

2023-09-02 13:28 UTC, vladislavStel commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/exception/ErrorHandler.java
> +    @ExceptionHandler(ConflictException.class)
изменил

2023-09-02 13:29 UTC, vladislavStel commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/event/service/EventService.java
> +    List<EventShortDto> findEventsBySearchQueryAndSort(String text, List<Long> categories, Boolean paid,
создал объект

2023-09-02 13:30 UTC, vladislavStel commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/category/controller/PublicCategoryController.java
> +                                           @RequestParam(name = "size", defaultValue = "10", required = false) int size) {
добавил валидацию

2023-09-03 04:40 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/event/controller/PrivateEventController.java
> +                                         @RequestParam(defaultValue = "10", required = false) int size) {
А здесь валидация?

2023-09-03 04:40 UTC, sergeymamonov commented on ewm-main-service/src/main/java/ru/practicum/ewm/main_service/location/dto/LocationDto.java
> +import lombok.*;
Значит нужно отключить wildcard import https://www.jetbrains.com/help/idea/creating-and-optimizing-imports.html#disable-wildcards-for-class

2023-09-03 04:49 UTC, sergeymamonov approved these changes
InvalidRequestParameterException("Field: eventDate. Error: must contain a date that has not yet arrived. ... - и при такой ошибке клиент получит 403 ошибку, которая говорит, что доступ к запрошенному ресурсу запрещен. При такой ошибке должен быть 400 - невалидные данные. Посмотрите, где используется исключение InvalidRequestParameterException, скорее всего в разных случаях могут использоваться разные исключения. Зависит от ситуации, при которой возникла ошибка, и статуса, который нужно вернуть.

2023-09-03 06:08 UTC, merged